### ISSUE TITLE
Failed to Sync with Dropbox - Windows 10

### ISSUE THREAD

**Issue by Flavio-Souza-BR** [baywolf-studios/BudgetBadger#79]
I'm getting the below error message to sync with Dropbox on windows 10.

![image](https://user-images.githubusercontent.com/106972944/172165346-80def6ad-6de9-4329-b0d3-f9028dc614c1.png)

**Comment by matthewpritchett** [comment]
@Flavio-Souza-BR thanks for the bug report! I was able to find the issue and have a fix committed that’s being built now. I should get a new release submitted tonight that fixes this issue. It ended up being from a breaking change in the database package I used that kept connections open after finishing using them so I would try to delete the file but it was obviously still on use.

**Comment by matthewpritchett** [comment]
Submitted to all the app stores. You should see the update shortly either today or tomorrow. I'll close the issue in a couple days if I haven't heard differently.

**Comment by Flavio-Souza-BR** [comment]
Hello,

Sorry I didn't respond sooner, I was away, I took a new test today and the error still persists.
The android application does not have this problem, only the Windows version.
I'm using the latest version available in the windows store v1.10.0.0, no, maybe the correction version has not yet been released in the Brazilian windows store.

![image](https://user-images.githubusercontent.com/106972944/173239919-0c57cb8e-d79c-41b5-8369-6750eb987a0a.png)

**Comment by matthewpritchett** [comment]
That's totally my fault. Apparently there was an error when I uploaded the new version (1.10.1). I'm resubmitting today and will let you know once it's deployed. Thanks!

**Comment by matthewpritchett** [comment]
@Flavio-Souza-BR Now it says it’s available in the Store. So you should see it now or in the next few hours depending.
